### ISSUE TITLE
Artillery script execution error: ERR_REQUIRE_ESM in @oclif/config plugin

### ISSUE THREAD

**Issue by aldousalvarez** [artilleryio/artillery#1933]
Version info: 
```
Artillery: 1.7.2 migrating to v.2.0.0-x
NodeJS: 16.14.2
```

Running this command: 
```
artillery run ${artilleryScriptLocation} --output report.json
```

I expected to see this happen:
```
It will proceed with the artillery load testing and will provide a report.json to see the results
```

Instead, this happened:
```
After migrating to version 2.0.0-x the @oclif/config has been added since the first release of [v2.0.0-x](https://github.com/artilleryio/artillery/blob/v2.0.0-0/package.json)

Err: Error: Command failed: artillery run ./packages/cactus-cmd-api-server/src/test/resources/artillery/benchmark-script.yaml --output report.json (node:700947) [ERR_REQUIRE_ESM] Error
  Plugin: artillery [ERR_REQUIRE_ESM]: require() of ES Module /******/cactus/node_modules/globby/index.js from /******/cactus/node_modules/@oclif/config/lib/plugin.js not supported. Instead
  change the require of index.js in /******/cactus/node_modules/@oclif/config/lib/plugin.js to a dynamic import() which is available in all CommonJS modules. module: @oclif/config@1.18.6 task: not
  loading commands, globby not found plugin: artillery root: /******/cactus/node_modules/artillery See more details with DEBUG=* (Use `node --trace-warnings ...` to show where the warning was
  created) › Error: command run not found

/@oclif/config/lib/plugin.js
Line 244 - const globbyPath = require.resolve('globby', {paths: [this.root, __dirname]})
Line 245 - globby = require(globbyPath)
```
Files being used:
```
artilleryScriptLocation
config:
  target: "{{ $processEnvironment.apiHost }}"
  phases:
    - duration: 3
      arrivalRate: 5
      name: Warm up
    - duration: 10
      arrivalRate: 5
      rampTo: 50
      name: Ramp up load
    - duration: 60
      arrivalRate: 50
      name: Sustained load
scenarios:
  - name: Load Test
    engine: skytrace
    flow:
      - get:
          url: "/api/v1/api-server/get-prometheus-exporter-metrics"

```

**Comment by hassy** [comment]
Hi @aldousalvarez 👋 The Artillery script provided runs without issues with Artillery v2. From a quick look at the linked GH issue in hyperledger/cacti it seems that the issue is with how you're invoking Artillery and the codebase that wraps it. There isn't anything that we can do in Artillery itself I'm afraid.

**Comment by Raynos** [comment]
I ran into the same issue trying to run `artillery` in my codebase and it does not work.

**Comment by Raynos** [comment]
```
(node:191537) [ERR_REQUIRE_ESM] Error Plugin: artillery [ERR_REQUIRE_ESM]: require() of ES Module /home/raynos/soundxyz/code/node_modules/.pnpm/globby@13.1.2/node_modules/globby/index.js from /home/raynos/soundxyz/code/node_modules/.pnpm/@oclif+config@1.18.10/node_modules/@oclif/config/lib/plugin.js not supported.
```

Basically I have some kind of dependency hell from `oclif-config` & globby where it assumes globby is CJS but its actually ESM and then it just fails to start.

**Comment by Raynos** [comment]
I get this issue due to using `pnpm` and it has a different node_modules layout.

**Comment by Raynos** [comment]
Its because I have globby @ 13 installed in my app instead of globby @ 11

Also the author of globby is a pain in the ass and made the breaking change to not support CJS

Also this config @oclif library is bad and makes assumptions and dynamically loads globby.

**Comment by Raynos** [comment]
The bug in artillery is that you are using https://www.npmjs.com/package/@oclif/config and that library is broken and you should stop using it.

**Comment by hassy** [comment]
thanks @Raynos! Should be fixed in the next release.

**Comment by hassy** [comment]
This is on `main` now and can be tested by installing [the canary release](https://github.com/artilleryio/artillery/actions/runs/5500232453/jobs/10023005056) `v2.0.0-34-ab3b474`

**Comment by Raynos** [comment]
@hassy I will try this canary release.

**Comment by Raynos** [comment]
```
aynos at system76-pc  
~/soundxyz/code/tools/load-testing on jake/tmp-test*
$ pnpm artillery --help
(node:277428) [ERR_REQUIRE_ESM] Error Plugin: artillery [ERR_REQUIRE_ESM]: require() of ES Module /home/raynos/soundxyz/code/node_modules/.pnpm/globby@13.1.2/node_modules/globby/index.js from /home/raynos/soundxyz/code/node_modules/.pnpm/@oclif+config@1.18.10/node_modules/@oclif/config/lib/plugin.js not supported.
Instead change the require of index.js in /home/raynos/soundxyz/code/node_modules/.pnpm/@oclif+config@1.18.10/node_modules/@oclif/config/lib/plugin.js to a dynamic import() which is available in all CommonJS modules.
module: @oclif/config@1.18.10
task: not loading commands, globby not found
plugin: artillery
root: /home/raynos/soundxyz/code/node_modules/.pnpm/artillery@2.0.0-34-ab3b474_@oclif+config@1.18.10_@types+node@16.18.24_typescript@5.1.3/node_modules/artillery
See more details with DEBUG=*
(Use `node --trace-warnings ...` to show where the warning was created)
Cloud-scale load testing. https://www.artillery.io

VERSION
  artillery/2.0.0-34-ab3b474 linux-x64 node-v18.16.1

USAGE
  $ artillery [COMMAND]

COMMANDS
  help  display help for artillery

raynos at system76-pc  
~/soundxyz/code/tools/load-testing on jake/tmp-test*
$ pnpm artillery --version
(node:277505) [ERR_REQUIRE_ESM] Error Plugin: artillery [ERR_REQUIRE_ESM]: require() of ES Module /home/raynos/soundxyz/code/node_modules/.pnpm/globby@13.1.2/node_modules/globby/index.js from /home/raynos/soundxyz/code/node_modules/.pnpm/@oclif+config@1.18.10/node_modules/@oclif/config/lib/plugin.js not supported.
Instead change the require of index.js in /home/raynos/soundxyz/code/node_modules/.pnpm/@oclif+config@1.18.10/node_modules/@oclif/config/lib/plugin.js to a dynamic import() which is available in all CommonJS modules.
module: @oclif/config@1.18.10
task: not loading commands, globby not found
plugin: artillery
root: /home/raynos/soundxyz/code/node_modules/.pnpm/artillery@2.0.0-34-ab3b474_@oclif+config@1.18.10_@types+node@16.18.24_typescript@5.1.3/node_modules/artillery
See more details with DEBUG=*
(Use `node --trace-warnings ...` to show where the warning was created)

        ___         __  _ ____
  _____/   |  _____/ /_(_) / /__  _______  __ ___
 /____/ /| | / ___/ __/ / / / _ \/ ___/ / / /____/
/____/ ___ |/ /  / /_/ / / /  __/ /  / /_/ /____/
    /_/  |_/_/   \__/_/_/_/\___/_/   \__  /
                                    /____/


VERSION INFO:

Artillery: 2.0.0-34-ab3b474
Node.js:   v18.16.1
OS:        linux

```

Did not resolve the issue, this can be reproduced by installing artillery & globby@13 side by side using the `pnpm` cli

**Comment by hassy** [comment]
Thanks @Raynos! it looks like an older version of `@oclif/config` is still being pulled in by other Oclif dependencies. Should be fixed in https://github.com/artilleryio/artillery/pull/1982

**Comment by Raynos** [comment]
```
~/soundxyz/code/tools/admin-tools on dev*
$ pnpm artillery --version
(node:336901) [ERR_REQUIRE_ESM] Error Plugin: artillery [ERR_REQUIRE_ESM]: require() of ES Module /home/raynos/soundxyz/code/node_modules/.pnpm/globby@13.1.2/node_modules/globby/index.js from /home/raynos/soundxyz/code/node_modules/.pnpm/@oclif+config@1.18.11/node_modules/@oclif/config/lib/plugin.js not supported.
Instead change the require of index.js in /home/raynos/soundxyz/code/node_modules/.pnpm/@oclif+config@1.18.11/node_modules/@oclif/config/lib/plugin.js to a dynamic import() which is available in all CommonJS modules.
module: @oclif/config@1.18.11
task: not loading commands, globby not found
plugin: artillery
root: /home/raynos/soundxyz/code/node_modules/.pnpm/artillery@2.0.0-34-8182082_@oclif+config@1.18.11_@types+node@16.18.24_typescript@5.1.3/node_modules/artillery
See more details with DEBUG=*
(Use `node --trace-warnings ...` to show where the warning was created)

        ___         __  _ ____
  _____/   |  _____/ /_(_) / /__  _______  __ ___
 /____/ /| | / ___/ __/ / / / _ \/ ___/ / / /____/
/____/ ___ |/ /  / /_/ / / /  __/ /  / /_/ /____/
    /_/  |_/_/   \__/_/_/_/\___/_/   \__  /
                                    /____/


VERSION INFO:

Artillery: 2.0.0-34-8182082
Node.js:   v18.16.1
OS:        linux
```

It still appears to be an issue

**Comment by Raynos** [comment]
```
$ cat pnpm-lock.yaml | grep '@oclif/config'
        version: 2.0.0-34-8182082(@oclif/config@1.18.11)(@types/node@16.18.24)(typescript@5.1.3)
  /@artilleryio/platform-fargate@1.0.5(@oclif/config@1.18.11):
      '@oclif/command': 1.8.31(@oclif/config@1.18.11)
      - '@oclif/config'
  /@oclif/command@1.8.31(@oclif/config@1.18.11):
      '@oclif/config': ^1
      '@oclif/config': 1.18.11
  /@oclif/config@1.18.11:
      '@oclif/config': 1.18.11
  /artillery@2.0.0-34-8182082(@oclif/config@1.18.11)(@types/node@16.18.24)(typescript@5.1.3):
      '@artilleryio/platform-fargate': 1.0.5(@oclif/config@1.18.11)
      - '@oclif/config'
raynos at system76-pc  
```

Here is the list of the places where config still comes up. Maybe this should be fixed in oclif itself.
